import Link from "next/link";
import { ArrowUpRight, Check, Play, Sparkles, WandSparkles } from "lucide-react";

export default function Home() {
  return (
    <div className="min-h-screen overflow-hidden bg-[#f7f8f5]">
      <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
        <Link href="/" className="display text-xl font-bold tracking-tight"><span className="mr-2 inline-block h-3 w-3 rounded-full bg-[#ee7967]" />cinevo<span className="text-[#0d8478]">.</span></Link>
        <nav className="hidden items-center gap-8 text-sm text-[#63716f] md:flex"><a href="#features">Features</a><a href="#workflow">How it works</a><a href="#preview">Studio</a></nav>
        <div className="flex items-center gap-3"><Link href="/login" className="hidden px-3 py-2 text-sm font-semibold md:block">Sign in</Link><Link href="/register" className="rounded-full bg-[#173b39] px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-[#173b39]/15 transition hover:-translate-y-0.5">Start creating <ArrowUpRight className="ml-1 inline h-4 w-4" /></Link></div>
      </header>
      <main>
        <section className="mx-auto grid max-w-7xl items-center gap-14 px-6 pb-24 pt-14 lg:grid-cols-[1fr_.9fr] lg:px-10 lg:pb-32 lg:pt-24">
          <div><div className="mb-7 flex items-center gap-2 text-sm font-semibold text-[#0d8478]"><Sparkles className="h-4 w-4" /> Your creative co-pilot</div><h1 className="display max-w-2xl text-6xl font-bold leading-[.98] text-[#173b39] sm:text-7xl">Turn sparks into <span className="text-[#ee7967]">stories.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#66736f]">Describe an idea, shape it with AI, and bring a polished video to life without leaving your creative flow.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/register" className="rounded-full bg-[#ee7967] px-6 py-4 font-semibold text-white shadow-xl shadow-[#ee7967]/20 transition hover:-translate-y-1">Create your first video <ArrowUpRight className="ml-2 inline h-4 w-4" /></Link><Link href="/create" className="rounded-full border border-[#d8e0db] bg-white px-6 py-4 font-semibold text-[#173b39] transition hover:bg-[#edf5f0]"><Play className="mr-2 inline h-4 w-4 fill-current" /> Explore the studio</Link></div><div className="mt-10 flex items-center gap-6 text-sm text-[#70807b]"><span><strong className="text-[#173b39]">10×</strong> faster planning</span><span><strong className="text-[#173b39]">4.9/5</strong> creator rating</span></div></div>
          <div id="preview" className="relative"><div className="absolute -right-12 -top-12 h-48 w-48 rounded-full bg-[#d4eee5] blur-3xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/70 bg-[#173b39] p-3 shadow-2xl shadow-[#173b39]/20"><div className="grain relative aspect-[.88] overflow-hidden rounded-[1.5rem] bg-[#cce7de] p-7"><div className="absolute inset-0 bg-gradient-to-br from-transparent via-transparent to-[#4b8d7b]/30" /><div className="relative flex items-center justify-between text-xs font-semibold uppercase tracking-[.2em] text-[#326c62]"><span>Project 014</span><span>60 sec</span></div><div className="absolute bottom-8 left-7 right-7"><div className="mb-5 flex items-end gap-3"><div className="h-32 w-16 rounded-t-full bg-[#ee7967]" /><div className="h-48 w-20 rounded-t-full bg-[#f6b597]" /><div className="h-24 w-14 rounded-t-full bg-[#6baf9c]" /><div className="h-40 w-16 rounded-t-full bg-[#173b39]" /></div><div className="rounded-2xl bg-white/80 p-4 backdrop-blur"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-semibold text-[#6d7a75]">AI VIDEO PLAN</span><WandSparkles className="h-4 w-4 text-[#ee7967]" /></div><p className="display text-xl font-bold text-[#173b39]">The quiet power of a new idea.</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#d7e5df]"><div className="h-full w-3/4 rounded-full bg-[#0d8478]" /></div></div></div></div></div><div className="absolute -bottom-5 -left-9 rounded-2xl border border-[#d5e7e1] bg-white p-4 shadow-xl"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#e0f4ed] text-[#0d8478]"><Check className="h-5 w-5" /></span><div><p className="text-xs font-bold text-[#173b39]">Scene plan ready</p><p className="text-xs text-[#7e8b86]">5 scenes · cinematic</p></div></div></div></div>
        </section>
        <section id="features" className="border-y border-[#e4e8e3] bg-white px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="mb-3 text-sm font-bold uppercase tracking-[.18em] text-[#ee7967]">Built for momentum</p><h2 className="display text-4xl font-bold text-[#173b39] sm:text-5xl">From blank page to watchable in minutes.</h2></div><div className="mt-14 grid gap-4 md:grid-cols-3"><Feature icon="01" title="Plan with clarity" text="Turn a loose thought into a focused hook, audience, and scene-by-scene plan." /><Feature icon="02" title="Make it feel yours" text="Shape the story in a living AI conversation that keeps your voice at the center." /><Feature icon="03" title="Ship the moment" text="Generate, track progress, and keep every finished video in one calm workspace." /></div></div></section>
        <section id="workflow" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="rounded-[2rem] bg-[#e4f1eb] px-7 py-12 sm:px-14"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.18em] text-[#0d8478]">A better creative loop</p><h2 className="display text-4xl font-bold leading-tight text-[#173b39]">The fun part is making decisions, not wrestling tools.</h2><Link href="/register" className="mt-8 inline-block rounded-full bg-[#173b39] px-5 py-3 text-sm font-semibold text-white">Open your studio <ArrowUpRight className="ml-1 inline h-4 w-4" /></Link></div><div className="grid gap-3 sm:grid-cols-3"><Step n="01" title="Describe" text="Start with a feeling, question, or rough idea." /><Step n="02" title="Shape" text="Collaborate with AI on the story and visuals." /><Step n="03" title="Create" text="Generate a polished video you can share." /></div></div></div></section>
      </main><footer className="border-t border-[#e4e8e3] px-6 py-8 text-sm text-[#71807a] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 sm:flex-row"><span className="display font-bold text-[#173b39]">cinevo.</span><span>Make something worth watching.</span><span>© 2026 Cinevo AI</span></div></footer>
    </div>
  );
}

function Feature({ icon, title, text }: { icon: string; title: string; text: string }) { return <div className="rounded-3xl border border-[#e4e8e3] bg-[#fbfcfa] p-7 transition hover:-translate-y-1 hover:shadow-lg"><span className="text-sm font-bold text-[#ee7967]">{icon}</span><h3 className="display mt-12 text-2xl font-bold text-[#173b39]">{title}</h3><p className="mt-3 leading-7 text-[#71807a]">{text}</p></div>; }
function Step({ n, title, text }: { n: string; title: string; text: string }) { return <div className="rounded-2xl bg-white/70 p-5"><span className="text-xs font-bold text-[#ee7967]">{n}</span><h3 className="display mt-8 text-xl font-bold text-[#173b39]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#71807a]">{text}</p></div>; }
